import { ReactNode } from "react";
import Head from "next/head";
import { useSession, signOut } from "next-auth/react";
import { Button, HStack } from "@chakra-ui/react";
interface ILayoutProps {
	children: ReactNode;
}

export function Layout({ children }: ILayoutProps) {
	const { data: session } = useSession();

	return (
		<div>
			<div>
				<Head>
					<title>Next Chakra Admin</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
			</div>
			<div className="left"></div>
			<div className="main">
				<div className="header">
					<HStack>
						<span>Signed in as {session?.user?.name}</span>
						<Button onClick={() => signOut()}>Sign out</Button>
					</HStack>
				</div>
				<div className="content">{children}</div>
			</div>
		</div>
	);
}
