import type { NextPage } from "next";
import Head from "next/head";
import { Button } from "@chakra-ui/react";
import { useSession, signIn, signOut } from "next-auth/react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
	const { data: session } = useSession();
	if (session) {
		return (
			<div className={styles.container}>
				<Head>
					<title>Next Chakra Admin</title>
					<meta name='description' content='Generated by create next app' />
					<link rel='icon' href='/favicon.ico' />
				</Head>

				<div>
					Signed in as {JSON.stringify(session)} <br />
					<Button onClick={() => signOut()}>Sign out</Button>
				</div>
			</div>
		);
	}
	return (
		<>
			Not signed in <br />
			<Button onClick={() => signIn()}>Sign in</Button>
		</>
	);
};

export default Home;
